const EMAIL_TEMPLATE_KEYS = {
  NEW_ORDER_PAYMENT: "new_order_payment",
  NEW_CUSTOMER_WELCOME: "new_customer_welcome",
  NEW_USER_AUTH_CREDENTIALS: "new_user_auth_credentials",
  ORDER_DELIVERY_ALERT: "order_delivery_alert",
  NEW_ORDER: "new_order",
  NEW_MEASUREMENT: "new_measurement",
  USER_INVITATION: "user_invitation",
  EMPLOYEE_INVITATION: "employee_invitation",
  EMPLOYEE_TASK_ASSIGNED: "employee_task_assigned",
};

const DEFAULT_EMAIL_TEMPLATES = [
  {
    key: EMAIL_TEMPLATE_KEYS.NEW_ORDER_PAYMENT,
    templateName: "New Order Payment",
    templateType: "customer",
    placeholders: [
      "{{user_name}}",
      "{{order_id}}",
      "{{order_date}}",
      "{{payment_id}}",
      "{{payment_method}}",
      "{{payment_status}}",
      "{{amount_paid}}",
      "{{currency}}",
      "{{order_total}}",
      "{{due_amount}}",
      "{{transaction_date}}",
      "{{order_url}}",
    ],
    enabled: true,
    subject: "Payment received for order {{order_id}}",
    body: `<p>Hi {{user_name}},</p><p>We received your payment for order <strong>{{order_id}}</strong>.</p><p>Paid: {{currency}} {{amount_paid}}<br/>Total: {{currency}} {{order_total}}<br/>Due: {{currency}} {{due_amount}}<br/>Status: {{payment_status}}</p><p><a href="{{order_url}}">View order details</a></p>`,
  },
  {
    key: EMAIL_TEMPLATE_KEYS.NEW_CUSTOMER_WELCOME,
    templateName: "New Customer Welcome",
    templateType: "customer",
    placeholders: [
      "{{customer_name}}",
      "{{customer_email}}",
      "{{customer_phone}}",
      "{{customer_address}}",
      "{{support_email}}",
    ],
    enabled: true,
    subject: "Welcome, {{customer_name}}",
    body: `<p>Hello {{customer_name}},</p><p>Thank you for joining us. Here are the details we have on file:</p><p>Email: {{customer_email}}<br/>Phone: {{customer_phone}}<br/>Address: {{customer_address}}</p><p>For questions or support, reach us at {{support_email}}.</p>`,
  },
  {
    key: EMAIL_TEMPLATE_KEYS.NEW_USER_AUTH_CREDENTIALS,
    templateName: "New User Auth Credentials",
    templateType: "user",
    placeholders: [
      "{{user_name}}",
      "{{user_email}}",
      "{{login_url}}",
      "{{temporary_password}}",
      "{{account_role}}",
    ],
    enabled: true,
    subject: "Your account credentials for StitchFlow",
    body: `<p>Hello {{user_name}},</p><p>Your account is ready.</p><p>Email: {{user_email}}<br/>Role: {{account_role}}<br/>Temporary password: {{temporary_password}}</p><p><a href="{{login_url}}">Login now</a> and change your password.</p>`,
  },
  {
    key: EMAIL_TEMPLATE_KEYS.ORDER_DELIVERY_ALERT,
    templateName: "Order Delivery Alert",
    templateType: "admin",
    placeholders: [
      "{{admin_name}}",
      "{{order_id}}",
      "{{customer_name}}",
      "{{customer_email}}",
      "{{delivery_date}}",
      "{{delivery_time}}",
      "{{delivery_address}}",
      "{{order_status}}",
      "{{assigned_driver}}",
      "{{notes}}",
      "{{admin_panel_url}}",
    ],
    enabled: true,
    subject: "Delivery alert: order {{order_id}}",
    body: `<p>Hello {{admin_name}},</p><p>Order <strong>{{order_id}}</strong> needs delivery attention.</p><p>Customer: {{customer_name}} ({{customer_email}})<br/>Date: {{delivery_date}} {{delivery_time}}<br/>Address: {{delivery_address}}<br/>Status: {{order_status}}<br/>Driver: {{assigned_driver}}<br/>Notes: {{notes}}</p><p><a href="{{admin_panel_url}}">Open admin panel</a></p>`,
  },
  {
    key: EMAIL_TEMPLATE_KEYS.NEW_ORDER,
    templateName: "New Order",
    templateType: "customer",
    placeholders: [
      "{{user_name}}",
      "{{order_id}}",
      "{{order_date}}",
      "{{order_status}}",
      "{{order_items}}",
      "{{order_total}}",
      "{{currency}}",
      "{{delivery_address}}",
      "{{estimated_delivery_date}}",
      "{{order_url}}",
    ],
    enabled: true,
    subject: "Your new order {{order_id}} is created",
    body: `<p>Hello {{user_name}},</p><p>Your order <strong>{{order_id}}</strong> has been created on {{order_date}}.</p><p>Status: {{order_status}}<br/>Items: {{order_items}}<br/>Total: {{currency}} {{order_total}}<br/>Delivery address: {{delivery_address}}<br/>Estimated delivery: {{estimated_delivery_date}}</p><p><a href="{{order_url}}">Track order</a></p>`,
  },
  {
    key: EMAIL_TEMPLATE_KEYS.NEW_MEASUREMENT,
    templateName: "New Measurement",
    templateType: "customer",
    placeholders: [
      "{{user_name}}",
      "{{measurement_id}}",
      "{{measurement_date}}",
      "{{measurement_type}}",
      "{{measurement_details}}",
      "{{taken_by}}",
      "{{notes}}",
      "{{next_appointment_date}}",
    ],
    enabled: true,
    subject: "New measurement recorded ({{measurement_id}})",
    body: `<p>Hello {{user_name}},</p><p>Your new measurement has been recorded.</p><p>Measurement ID: {{measurement_id}}<br/>Date: {{measurement_date}}<br/>Type: {{measurement_type}}<br/>Details: {{measurement_details}}<br/>Taken by: {{taken_by}}<br/>Notes: {{notes}}<br/>Next appointment: {{next_appointment_date}}</p>`,
  },
  {
    key: EMAIL_TEMPLATE_KEYS.USER_INVITATION,
    templateName: "User Invitation",
    templateType: "user",
    placeholders: [
      "{{user_name}}",
      "{{invitation_url}}",
      "{{invitation_token}}",
      "{{account_role}}",
      "{{expiry_hours}}",
    ],
    enabled: true,
    subject: "You're invited to join StitchFlow",
    body: `<p>Hello {{user_name}},</p><p>You've been invited to join StitchFlow.</p><p>Click the button below to set up your account and get started. This invitation will expire in {{expiry_hours}} hours.</p><p style="text-align:center;margin:32px 0"><a href="{{invitation_url}}" style="display:inline-block;padding:14px 32px;background-color:#111827;color:#ffffff;text-decoration:none;border-radius:8px;font-weight:600;font-size:16px">Accept Invitation</a></p><p>Or copy and paste this link in your browser:</p><p style="word-break:break-all;font-size:13px;color:#6b7280">{{invitation_url}}</p>`,
  },
  {
    key: EMAIL_TEMPLATE_KEYS.EMPLOYEE_INVITATION,
    templateName: "Employee Invitation",
    templateType: "employee",
    placeholders: [
      "{{employee_name}}",
      "{{invitation_url}}",
      "{{invitation_token}}",
      "{{expiry_hours}}",
    ],
    enabled: true,
    subject: "You're invited to join StitchFlow as an employee",
    body: `<p>Hello {{employee_name}},</p><p>You've been invited to join StitchFlow as an employee.</p><p>Click the button below to set up your account and get started. This invitation will expire in {{expiry_hours}} hours.</p><p style="text-align:center;margin:32px 0"><a href="{{invitation_url}}" style="display:inline-block;padding:14px 32px;background-color:#111827;color:#ffffff;text-decoration:none;border-radius:8px;font-weight:600;font-size:16px">Accept Invitation</a></p><p>Or copy and paste this link in your browser:</p><p style="word-break:break-all;font-size:13px;color:#6b7280">{{invitation_url}}</p>`,
  },
  {
    key: EMAIL_TEMPLATE_KEYS.EMPLOYEE_TASK_ASSIGNED,
    templateName: "New Task Assigned",
    templateType: "employee",
    placeholders: [
      "{{employee_name}}",
      "{{order_id}}",
      "{{task_name}}",
      "{{order_status}}",
      "{{customer_name}}",
      "{{dashboard_url}}",
    ],
    enabled: true,
    subject: "New task assigned: {{task_name}} for order {{order_id}}",
    body: `<p>Hello {{employee_name}},</p><p>You have been assigned a new task for order <strong>{{order_id}}</strong>.</p><p>Task: {{task_name}}<br/>Order Status: {{order_status}}<br/>Customer: {{customer_name}}</p><p style="text-align:center;margin:32px 0"><a href="{{dashboard_url}}" style="display:inline-block;padding:14px 32px;background-color:#111827;color:#ffffff;text-decoration:none;border-radius:8px;font-weight:600;font-size:16px">View in Dashboard</a></p>`,
  },
];

module.exports = {
  EMAIL_TEMPLATE_KEYS,
  DEFAULT_EMAIL_TEMPLATES,
};
